// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cs_backend.Models;

#nullable disable

namespace cs_backend.Migrations
{
    [DbContext(typeof(TenttiDBContext))]
    [Migration("20230118122852_initial create")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cs_backend.Models.Kysymys", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("kys_nimi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tentti_id")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Kysymykset");
                });

            modelBuilder.Entity("cs_backend.Models.Tentti", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("min_pisteet")
                        .HasColumnType("integer");

                    b.Property<string>("ten_nimi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tentti_Pvm")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Tentit");
                });

            modelBuilder.Entity("cs_backend.Models.Vastaus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("kysymys_id")
                        .HasColumnType("integer");

                    b.Property<bool>("onko_oikein")
                        .HasColumnType("boolean");

                    b.Property<int>("pisteet")
                        .HasColumnType("integer");

                    b.Property<string>("vas_nimi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Vastaukset");
                });
#pragma warning restore 612, 618
        }
    }
}
